name:                aoc2024
version:             0.1.0.0
github:              "githubuser/aoc2024"
license:             BSD-3-Clause
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2024 Author name here"

extra-source-files:
- README.md
- CHANGELOG.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/aoc2024#readme>

dependencies:
- base >= 4.7 && < 5
- containers >= 0.6.7 && < 1
- deepseq >= 1.4.8.1 && < 2
- hashable >= 1.4.4.0 && < 2
- megaparsec >= 9.5.0 && < 10
- MemoTrie >= 0.6.11 && < 1
- text >= 2.0.2 && < 3
- unordered-containers >= 0.2.20 && < 1
- vector >= 0.13.1.0 && < 0.14
- vector-algorithms >= 0.9.0.2 && < 1

default-language: Haskell2010

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-export-lists
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints

library:
  source-dirs: src

executables:
  p01:
    main:                Main.hs
    source-dirs:         app/day01
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - aoc2024
  p02:
    main:                Main.hs
    source-dirs:         app/day02
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - aoc2024
  p03:
    main:                Main.hs
    source-dirs:         app/day03
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - aoc2024
  p04:
    main:                Main.hs
    source-dirs:         app/day04
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - aoc2024
  p05:
    main:                Main.hs
    source-dirs:         app/day05
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - aoc2024
  p06:
    main:                Main.hs
    source-dirs:         app/day06
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -O2
    dependencies:
    - aoc2024
  p07:
    main:                Main.hs
    source-dirs:         app/day07
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - aoc2024
  p08:
    main:                Main.hs
    source-dirs:         app/day08
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - aoc2024
  p09:
    main:                Main.hs
    source-dirs:         app/day09
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - aoc2024
  p10:
    main:                Main.hs
    source-dirs:         app/day10
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - aoc2024
  p11:
    main:                Main.hs
    source-dirs:         app/day11
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -O2
    dependencies:
    - aoc2024
  p12:
    main:                Main.hs
    source-dirs:         app/day12
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - aoc2024

tests:
  aoc2024-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - aoc2024
